# Generated by Django 4.2.7 on 2026-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment')], default='ONLINE', max_length=20),
        ),
    ]
